PROJECT_NAME = 'Facial Classifier'
PROJECT_VERSION = '0.1'
PROJECT_DESCRIPTION = 'Facial classifier using machine learning'
PROJECT_URL = 'https://github.com/sangjung0/Facial_Classifier'
PROJECT_AUTHOR = 'sangjung'
PROJECT_AUTHOR_EMAIL = 'sangjung245@gmail.com'
FACE = 'face'
NOSE = 'nose'
MOUTH = 'mouth'
EYE = 'eye'
FACE_MODEL = './face_detector/model/haarcascade_frontalface_default.xml'
EYE_MODEL = './face_detector/model/haarcascade_eye.xml'
RUN = 100
STOP = 0
PAUSE = 101
END_OF_LOAD = 102