PROJECT_NAME = 'Facial Classifier'
PROJECT_VERSION = '0.1'
PROJECT_DESCRIPTION = 'Facial classifier using machine learning'
PROJECT_URL = 'https://github.com/sangjung0/Facial_Classifier'
PROJECT_AUTHOR = 'sangjung'
PROJECT_AUTHOR_EMAIL = 'sangjung245@gmail.com'