PROCESSOR_STOP:int = 1
PROCESSOR_PAUSE:int = 2
PROCESSOR_START:int = 3

CONVERTER_TIMEOUT:int = 1

FACE_CLASSIFIER_THRESHOLD:float = 0.4
FACE_CLASSIFIER_MAX_FACE:int = 5

SHAPE_PREDICTOR_PATH:str = './resource/shape_predictor_68_face_landmarks.dat'
FACE_RECOGNITION_MODEL:str = './resource/dlib_face_recognition_resnet_model_v1.dat'

MAX_BUF_SIZE:int = 2

CACHE_SIZE:int = 11

HISTOGRAM_THRESHOLD:float = 0.88

SCHEDULER_MAX_PATH_COUNT:int = 4
SCHEDULER_BUF_SIZE:int = 4
SCHEDULER_PACKET_SIZE:int = 4

GRIDE_SIZE:int = 1

SCHEDULER_LOGER:bool = True